apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bahmq1cqo-go 
  janus-idp.io/tekton: bahmq1cqo-go
  backstage.io/kubernetes-id: bahmq1cqo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bahmq1cqo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  